export const tutorMenus = [
  {
    icon: 'fi fi-rr-user',
    title: 'Profile settings',
    description: 'Expert profile settings can be edited and updated here.',
    path: '/users/profile',
    key: 'menu-my-profile-1'
  },

  {
    icon: 'fi fi-rs-chalkboard-user',
    title: 'Group sessions',
    description: 'Group sessions posted by the expert will be displayed here.',
    path: '/users/groupsession',
    key: 'menu-webinar-list'
  },
  {
    icon: 'fi fi-rs-chalkboard-user',
    title: 'Create a group sessions',
    description: 'The expert can create a new group session from here.',
    path: '/users/groupsession/create',
    key: 'menu-webinar-create'
  },
  // {
  //   icon: 'fi fi-rr-book-alt',
  //   title: 'Courses List',
  //   description: 'Courses created by the expert will be listed here.',
  //   path: '/users/courses',
  //   key: 'menu-course-list'
  // },
  // {
  //   icon: 'fi fi-rr-book-alt',
  //   title: 'Create a course',
  //   description: 'The expert can create a new course.',
  //   path: '/users/courses/create',
  //   key: 'menu-course-create'
  // },

  {
    icon: 'fi fi-rs-coins',
    title: 'Payout request',
    description: 'Shows the earning and payout status of the expert.',
    path: '/users/payout/request',
    key: 'menu-my-payout-1'
  },
  {
    icon: 'fi fi-rr-calendar-clock',
    title: 'Set your calendar',
    description: 'Allows the expert to book appointments for 1‑on‑1 sessions.',
    path: '/users/1on1sessions',
    key: 'menu-my-schedule'
  },
  {
    icon: 'fi fi-rr-calendar',
    title: 'Upcoming appointments',
    description: 'Appointments scheduled by the expert for 1‑on‑1 sessions.',
    path: '/users/appointments',
    key: 'menu-my-appointment'
  },
  {
    icon: 'fi fi-rr-calendar-check',
    title: 'Group class bookings',
    description: 'Appointments scheduled by the expert for group classes.',
    path: '/users/appointments',
    key: 'menu-my-appointment-1'
  },
  {
    icon: 'fi fi-rr-chart-histogram',
    title: 'Earnings dashboard',
    description: 'Earnings generated by the expert.',
    path: '/users/payout/request',
    key: 'menu-my-payout-2'
  },
  {
    icon: 'fi fi-rr-credit-card',
    title: 'Add a bank info',
    description: 'The expert adds PayPal and bank accounts for payouts.',
    path: '/users/payout/account/create',
    key: 'menu-my-payout'
  },
  {
    icon: 'fi fi-rr-user-add',
    title: 'Invite a Friend',
    description: 'Experts can invite their contacts to the platform.',
    path: '/users/profile',
    key: 'menu-my-profile'
  }

];

export const studentMenus = [
  {
    icon: 'fi fi-rr-user',
    title: 'Profile settings',
    description: 'Client profile settings can be edited and updated here.',
    path: '/users/profile',
    key: 'menu-my-profile-1'
  },
  {
    icon: 'fi fi-rr-comment-alt',
    title: 'Assigned Experts',
    description: 'View your AI query submissions and assigned experts.',
    path: '/users/ai-queries',
    key: 'menu-ai-queries'
  },
  {
    icon: 'fi fi-rs-chalkboard-user',
    title: 'Browse group sessions',
    description: 'Browse group sessions from experts assigned to your group classes. Filter by category and subcategory.',
    path: '/users/browse-group-sessions',
    key: 'menu-categories'
  },
  // {
  //   icon: 'fi fi-rr-book-alt',
  //   title: 'My purchased courses',
  //   description: 'Courses purchased by the client will be listed here.',
  //   path: '/users/my-courses',
  //   key: 'menu-my-course'
  // },
  {
    icon: 'fi fi-rr-calendar',
    title: 'Upcoming appointments',
    description: 'Appointments booked by the client for 1‑on‑1 sessions.',
    path: '/users/lessons',
    key: 'menu-my-lesson'
  },
  {
    icon: 'fi fi-rr-credit-card',
    title: 'My Transactions ',
    description: 'Clients see all purchases/transactions for 1‑on‑1 and webinars here.',
    path: '/users/transaction',
    key: 'menu-my-transaction'
  },
  {
    icon: 'fi fi-rr-comment-dollar',
    title: 'Refund Request',
    description: 'Refund requests for the client will be displayed.',
    path: '/users/refund/request',
    key: 'menu-my-refund'
  }
];
